name: Build
on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Show pwd path
        run: pwd
      - name: Show tree structure
        run: tree -a -L 4
      - name: Get repository code
        uses: actions/checkout@v3
