name: Build
on:
  workflow_dispatch:

jobs:
  buuid-all:
    runs-on: ubuntu-latest
    steps:
      - name: Show Path
        run: pwd
      - name: Get repository code
        uses: actions/checkout@v3
